# Generated by Django 4.0.4 on 2022-05-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_db', '0002_member_delete_family_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='kinship_deg',
            new_name='kinship',
        ),
    ]
