# Generated by Django 4.0.4 on 2022-05-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_db', '0003_rename_kinship_deg_member_kinship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='kinship',
            new_name='kinship_deg',
        ),
    ]
